---
title: "lab-07-simpsons.Rmd"
author: "Raghad mohmmed "
date: "19 March 2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages

```{r load_libraries, message=FALSE}
library(tidyverse) 
library(mosaicData)
```


## Exercises


1.  
```{r whickham}
?Whickham
```
    
Your answer:observational , Because they notice a person's health status after a period of time

2.  
```{r observations}
nrow(Whickham)
```

Your answer;
ىobs 1314  
Each row represents whether the person is alive or dead, is he a smoker or not, and how old he is

3.  

```{r number_variables}
ncol(Whickham)
```

Your answer:3 var , "outcome" "smoker"  "age"  

```{r var_type}
unique(Whickham$outcome)
unique(Whickham$smoker)
unique(Whickham$age)
```

Your answer: 

```{r plot_outcome}
ggplot(Whickham, aes(x = outcome)) +
  geom_bar()
```


```{r plot_smoker}
ggplot(Whickham, aes(x = smoker)) +
  geom_bar()
```

```{r plot_age}
ggplot(Whickham, aes(x = age)) +
  geom_boxplot()
```


4. 

```{r plot_smokeVSincome_1}
ggplot(data=Whickham, aes(x=smoker, y=outcome, color=outcome)) + geom_bar(stat="identity")

```

Knit, commit, and push to github.

5. 

```{r plot_smokeVSincome_2}
Whickham %>%
  count(smoker, outcome)
```

6.

```{r age_cat}

```

7. 

```{r plot_smokeVSincome_3}

```

Knit, commit, and push to github.